"""Initial migration

Revision ID: cbdd1d6c8680
Revises: 
Create Date: 2026-04-04 17:09:31.240021+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdd1d6c8680'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fin_kod')
    )
    op.create_index(op.f('ix_auth_fin_kod'), 'auth', ['fin_kod'], unique=True)
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('cv_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_path'),
    sa.UniqueConstraint('fin_kod'),
    sa.UniqueConstraint('fin_kod')
    )
    op.create_index(op.f('ix_cv_id'), 'cv', ['id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(), nullable=False),
    sa.Column('edu_code', sa.String(length=7), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edu_code'),
    sa.UniqueConstraint('fin_kod')
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_table('education_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edu_code', sa.String(length=7), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_translations_id'), 'education_translations', ['id'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('exp_code', sa.String(length=7), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exp_code')
    )
    op.create_index(op.f('ix_experience_id'), 'experience', ['id'], unique=False)
    op.create_table('experience_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exp_code', sa.String(length=7), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_translations_id'), 'experience_translations', ['id'], unique=False)
    op.create_table('inter_corp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inter_corp_code', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inter_corp_users_id'), 'inter_corp_users', ['id'], unique=False)
    op.create_table('international_coorperations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('inter_corp_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_international_coorperations_id'), 'international_coorperations', ['id'], unique=False)
    op.create_table('international_coorperations_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('inter_corp_code', sa.String(), nullable=False),
    sa.Column('inter_corp_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_international_coorperations_translations_id'), 'international_coorperations_translations', ['id'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('lang_serial', sa.String(), nullable=True),
    sa.Column('language_short_name', sa.String(), nullable=False),
    sa.Column('language_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    op.create_table('language_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('lang_serial', sa.String(), nullable=True),
    sa.Column('language_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_translations_id'), 'language_translations', ['id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('scopus_url', sa.Text(), nullable=True),
    sa.Column('webofscience_url', sa.Text(), nullable=True),
    sa.Column('google_scholar_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fin_kod')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('otp', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_id'), 'otp', ['id'], unique=False)
    op.create_table('research_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.String(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_code')
    )
    op.create_index(op.f('ix_research_areas_id'), 'research_areas', ['id'], unique=False)
    op.create_table('research_areas_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.String(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_code')
    )
    op.create_index(op.f('ix_research_areas_translations_id'), 'research_areas_translations', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fin_kod'),
    sa.UniqueConstraint('fin_kod')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('user_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('scientific_degree_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_translations_id'), 'user_translations', ['id'], unique=False)
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('work_serial', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_id'), 'work', ['id'], unique=False)
    op.create_table('work_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_serial', sa.String(), nullable=True),
    sa.Column('work_place', sa.String(), nullable=False),
    sa.Column('duty', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_translations_id'), 'work_translations', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('article_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fin_kod'], ['auth.fin_kod'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_code')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('bios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('bio_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fin_kod'], ['auth.fin_kod'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bio_code'),
    sa.UniqueConstraint('fin_kod')
    )
    op.create_index(op.f('ix_bios_id'), 'bios', ['id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('publication_code', sa.Text(), nullable=False),
    sa.Column('publication_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fin_kod'], ['auth.fin_kod'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_code')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_table('scientific_degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('scientific_degree_code', sa.String(length=10), nullable=False),
    sa.Column('scientific_degree_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fin_kod'], ['user.fin_kod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_degrees_id'), 'scientific_degrees', ['id'], unique=False)
    op.create_table('scientific_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fin_kod', sa.String(length=7), nullable=False),
    sa.Column('scientific_name_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fin_kod'], ['auth.fin_kod'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fin_kod'),
    sa.UniqueConstraint('scientific_name_code')
    )
    op.create_index(op.f('ix_scientific_names_id'), 'scientific_names', ['id'], unique=False)
    op.create_table('article_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('article_code', sa.Text(), nullable=False),
    sa.Column('article_field', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_code'], ['articles.article_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_translations_id'), 'article_translations', ['id'], unique=False)
    op.create_table('bio_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('bio_code', sa.Text(), nullable=False),
    sa.Column('bio_field', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bio_code'], ['bios.bio_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_translations_id'), 'bio_translations', ['id'], unique=False)
    op.create_table('publication_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('publication_code', sa.Text(), nullable=False),
    sa.Column('publication_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publication_code'], ['publications.publication_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_translations_id'), 'publication_translations', ['id'], unique=False)
    op.create_table('scientific_name_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('scientific_name_code', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scientific_name_code'], ['scientific_names.scientific_name_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_name_translations_id'), 'scientific_name_translations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scientific_name_translations_id'), table_name='scientific_name_translations')
    op.drop_table('scientific_name_translations')
    op.drop_index(op.f('ix_publication_translations_id'), table_name='publication_translations')
    op.drop_table('publication_translations')
    op.drop_index(op.f('ix_bio_translations_id'), table_name='bio_translations')
    op.drop_table('bio_translations')
    op.drop_index(op.f('ix_article_translations_id'), table_name='article_translations')
    op.drop_table('article_translations')
    op.drop_index(op.f('ix_scientific_names_id'), table_name='scientific_names')
    op.drop_table('scientific_names')
    op.drop_index(op.f('ix_scientific_degrees_id'), table_name='scientific_degrees')
    op.drop_table('scientific_degrees')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_bios_id'), table_name='bios')
    op.drop_table('bios')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_work_translations_id'), table_name='work_translations')
    op.drop_table('work_translations')
    op.drop_index(op.f('ix_work_id'), table_name='work')
    op.drop_table('work')
    op.drop_index(op.f('ix_user_translations_id'), table_name='user_translations')
    op.drop_table('user_translations')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_research_areas_translations_id'), table_name='research_areas_translations')
    op.drop_table('research_areas_translations')
    op.drop_index(op.f('ix_research_areas_id'), table_name='research_areas')
    op.drop_table('research_areas')
    op.drop_index(op.f('ix_otp_id'), table_name='otp')
    op.drop_table('otp')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_language_translations_id'), table_name='language_translations')
    op.drop_table('language_translations')
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_international_coorperations_translations_id'), table_name='international_coorperations_translations')
    op.drop_table('international_coorperations_translations')
    op.drop_index(op.f('ix_international_coorperations_id'), table_name='international_coorperations')
    op.drop_table('international_coorperations')
    op.drop_index(op.f('ix_inter_corp_users_id'), table_name='inter_corp_users')
    op.drop_table('inter_corp_users')
    op.drop_index(op.f('ix_experience_translations_id'), table_name='experience_translations')
    op.drop_table('experience_translations')
    op.drop_index(op.f('ix_experience_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_education_translations_id'), table_name='education_translations')
    op.drop_table('education_translations')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_cv_id'), table_name='cv')
    op.drop_table('cv')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_index(op.f('ix_auth_fin_kod'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
